#ifndef THERMOMETER_ONEWIRE_ROM_CMD_H
#define THERMOMETER_ONEWIRE_ROM_CMD_H

#define OW_SEARCH_ROM   0xF0
#define OW_READ_ROM     0x33
#define OW_MATCH_ROM    0x55
#define OW_SKIP_ROM     0xCC
#define OW_ALARM_SEARCH 0xEC

#endif //THERMOMETER_ONEWIRE_ROM_CMD_H
